# config.yaml (my configuration)

# --- Server Settings ---
port: 2500
host: "0.0.0.0" # Listen on all network interfaces

# --- Core Paths ---
# Path to the directory containing the web front-end files.
# Resolved relative to the server's location (__dirname).
wwwRoot: "www"

# IMPORTANT: The root directory for projects the server manages/modifies.
# For security and clarity, it's STRONGLY recommended to use an ABSOLUTE path
# in your personal config file (e.g., C:\Users\You\Projects or /Users/you/projects).
# If relative, it's resolved relative to the server's location.
projectRootDir: "/Users/rob/src/snipletsWebServer/www"

# IMPORTANT: List of ABSOLUTE paths the server is allowed to search within.
# Add the ABSOLUTE paths to your project areas in your personal config.
# This is CRUCIAL for security and functionality.
# Leaving this empty or incorrect severely limits the server.
searchRoots:
  - "/Users/rob"

# Optional: Path for storing backups of modified files.
# Resolved relative to the server's location (__dirname).
# Example: "backups" or "../file_backups"
oldVersionsPath: "/Users/rob/oldVersions"

# --- HTTPS Configuration (Optional) ---
# Paths are relative to the server's location (__dirname).
# Set keyPath and certPath to enable HTTPS.
https:
  keyPath: null # e.g., "certs/server.key"
  certPath: null # e.g., "certs/server.crt"

# --- Application Paths ---
# Define paths to applications used by 'openMappings'.
# ADJUST THESE PATHS for your specific OS and installation locations in your personal config.
# Use command names (like 'code') if they are in your system's PATH, otherwise provide full paths.
applications:
  vscode: "code"    # Try command name first (if 'code' is in PATH)
  chrome: "/Applications/Google Chrome.app" # macOS example
  # chrome: "C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe" # Windows example
  vlc: "vlc"        # Try command name first
  preview: "preview"  # macOS specific - 'open' package might handle default image viewer elsewhere
  explorer: "explorer" # Windows specific command for file explorer
  finder: "open"      # macOS specific command to open folders in Finder (using 'open' works)
  xdg-open: "xdg-open" # Linux standard command for opening files/folders

# --- File Type Opening Preferences ---
# Maps file extensions (keys) to a list of application keys (values) defined in "applications".
# The server will try these applications in the order listed when opening a file of that type.
openMappings:
  ".html":
    - "vscode"
    - "chrome"
  ".js":
    - "vscode"
  ".css":
    - "vscode"
  ".md":
    - "vscode"
  ".json":
    - "vscode"
  ".yaml":
    - "vscode"
  ".yml":
    - "vscode"
  ".svg":
    - "chrome"
    - "vscode"
    - "inkscape"
  ".png":
    - "chrome"
    - "preview" # Consider removing macOS specific alias or handle in code
  ".jpg":
    - "chrome"
    - "preview"
  ".jpeg":
    - "chrome"
    - "preview"
  ".gif":
    - "chrome"
    - "preview"
  ".pdf":
    - "chrome"
  ".mp4":
    - "chrome"
    - "vlc"
  ".mkv":
    - "vlc"
  # Add mappings for other file types as needed

# --- Web Root Mappings (Optional) ---
# Used to map local file system paths to URLs, potentially for generating
# preview links or other integrations.
webRoots:
  # Example: Map local project path to a running dev server URL
   - path: "/Users/rob/src/devHubServer/www"
     url: "http://localhost:2500"
  #
   - path: "C:\\Users\\You\\Projects\\my-api\\docs" # Windows example
     url: "http://localhost:8080"